version: "3.8"

services:
  backend:
    build:
      context: ../Python-api/ # Caminho para o diretório do backend onde está o Dockerfile
      dockerfile: Dockerfile # Nome do Dockerfile (opcional se for o padrão 'Dockerfile')
    container_name: python-back-nest
    ports:
      - "2001:2001"

  frontend:
    build:
      context: ./ # Caminho para o diretório do frontend onde está o Dockerfile
      dockerfile: Dockerfile # Nome do Dockerfile (opcional se for o padrão 'Dockerfile')
    container_name: python-front-next
    ports:
      - "2000:2000"
